version: "3"

networks:
  nginx-php81-postgres14:

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - nginx-php81-postgres14

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_php
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/app
    depends_on:
      - postgres
    networks:
      - nginx-php81-postgres14

  # postgres
  postgres:
    image: postgres:14.2-alpine
    container_name: symfony_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: usergroups
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATE: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
    networks:
      - nginx-php81-postgres14